version: "3.8"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: very_secure
      POSTGRES_DB: scraper
    ports:
      - "5432:5432"
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    command: postgres -c 'max_connections=250'
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - api
    restart: always
    ports:
      - "8080:80"

  app:
    build:
      context: ./client
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      - NODE_ENV=production
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - NODE_ENV=production
      - PGHOST=postgres
      - PGUSER=postgres
      - PGDATABASE=scraper
      - PGPASSWORD=very_secure
      - PGPORT=5432
